language: node_js
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm run build
  - npm test
after_success:
  - npm run coverage
env:
  matrix:
    secure: JoD0jQlskoVZtgKad2+WvHprb5Larhj4oodZEuSsvjGYt3FLhNufwyFVbdHq9UWHXZc9uKfCdfbI/Dw5AOZxGcmL6XIy9KTd9OBnjTRUV2VEbPbCLcHYZdIMHNwgdKR12Oi1KMqYNAwF9VCsbXtmucrO4PgmoWHdUbn41j2bVI+s+F9DlBzUlSjD0u32BYELANYsG7/eE9aL7e2z82hJJHv40E3RCf5lGPeNMxMDJrAU2nOv8KPUYpiYBcxLKHFs879rs24nbXFh2nPF9FOh0pGoK878oUu4WIAmoo8Cmr1JWEq5rInk4KsRrZ+vPZ4CjdWX4Wt+bwal8PGMsOei2Jg9U4qHucsYSAo3eVeDNT9mIiP3fWnDv5koAxzrOc40ox89jN7THn0HE0w9doGfGCsIwZVqeuLjt8LaGXcaWioWRvwiECNRmxD13H4d+vjx/tct7m3dYLn9KYPAFPq8WnydR6ihAyJ7nKh3xZrwWbkIKLU/YkEmelOfVWKba5lfnKnhWsFwX+rPv6vo1AWdXiFnXjwWeE7UAyshqDN3dPuX4pwlN/HWaEqgoC1/C2alUXwu6libzVxj7cN7MIkEAbiO1HyGoRhzk3XIRRikL2Qs/ngHWzLvItkhiiNEc369l98qujtuULqhUhqoZK3O5UjoOQyxfUM0EN7nwOdE1Uo=
